import { useState, useEffect, useRef } from 'react';
import { StatusBar } from 'expo-status-bar';
import {
  StyleSheet, Text, View, SafeAreaView, Pressable,
  Dimensions, ScrollView, PanResponder, Vibration,
} from 'react-native';
import { createAudioPlayer, setAudioModeAsync } from 'expo-audio';

// ══════════════════════════════════════════════
//  Constants
// ══════════════════════════════════════════════
const initialBoard = [
  ['♜','♞','♝','♛','♚','♝','♞','♜'],
  ['♟','♟','♟','♟','♟','♟','♟','♟'],
  ['','','','','','','',''],
  ['','','','','','','',''],
  ['','','','','','','',''],
  ['','','','','','','',''],
  ['♙','♙','♙','♙','♙','♙','♙','♙'],
  ['♖','♘','♗','♕','♔','♗','♘','♖'],
];
const whitePieces = ['♙','♖','♘','♗','♕','♔'];
const blackPieces = ['♟','♜','♞','♝','♛','♚'];
const PIECE_VALUES = { '♙':1,'♟':1,'♘':3,'♞':3,'♗':3,'♝':3,'♖':5,'♜':5,'♕':9,'♛':9,'♔':0,'♚':0 };
const SAN_LETTER = { '♔':'K','♚':'K','♕':'Q','♛':'Q','♖':'R','♜':'R','♗':'B','♝':'B','♘':'N','♞':'N','♙':'','♟':'' };

const THEMES = {
  classic: { light:'#f0d9b5', dark:'#b58863', accent:'#e2b96f' },
  green:   { light:'#ffffdd', dark:'#86a666', accent:'#9ec46f' },
  dark:    { light:'#6a6a6a', dark:'#2e2e2e', accent:'#aaaaaa' },
  blue:    { light:'#dee3e6', dark:'#8ca2ad', accent:'#8ca2ad' },
};

const screenW = Dimensions.get('window').width;
const BORDER = 3;
const BOARD = Math.min(screenW - 16, 400);
const SQ = Math.floor((BOARD - BORDER * 2) / 8);
const PLAY = SQ * 8;

// ══════════════════════════════════════════════
//  Game state (module-level, like the web globals)
// ══════════════════════════════════════════════
let gameBoard = [];
let currentTurn = 'white';
let enPassantTarget = null;
let castlingRights = { whiteKing:true, whiteQueen:true, blackKing:true, blackQueen:true };
let capturedByWhite = [], capturedByBlack = [];
let boardHistory = [], moveHistory = [];
let lastMove = null, halfMoveClock = 0, pendingSAN = null;
let positionCounts = {};
let gameMode = '', botDifficulty = '', over = false;
let whiteTime = 0, blackTime = 0, increment = 0, noTimer = false;
let startMinutes = 0, startIncrement = 0;
let pendingMode = '', pendingDifficulty = '';

// UI state (module-level so gesture handlers always read live values)
let screen = 'home';
let selected = null, targets = [], flipped = false;
let promo = null, result = null, thinking = false, status = '';
let theme = 'classic', autoQueen = false, soundOn = true;
let hint = null, premove = null;
let dragging = null, dragMoved = false, dragPremove = false;
let dragStart = null;
let score = { white: 0, black: 0, draws: 0 };

const TH = () => THEMES[theme];

// ── Helpers ──
const isWhite = (p) => whitePieces.includes(p);
const isBlack = (p) => blackPieces.includes(p);
const isCurrentPlayer = (p) => currentTurn === 'white' ? isWhite(p) : isBlack(p);
const isEnemy = (p, t) => !!t && ((isWhite(p) && isBlack(t)) || (isBlack(p) && isWhite(t)));
const isEmpty = (r, c) => gameBoard[r][c] === '';
const inBounds = (r, c) => r >= 0 && r < 8 && c >= 0 && c < 8;
const fmt = (s) => noTimer ? '∞' : `${Math.floor(Math.max(0,s)/60).toString().padStart(2,'0')}:${(Math.max(0,s)%60).toString().padStart(2,'0')}`;
const buzz = (ms) => { if (soundOn) { try { Vibration.vibrate(ms); } catch (e) {} } };

// ── Sound (WAV tones generated by make-sounds.js) ──
const SOUND_FILES = {
  move:     require('./assets/sounds/move.wav'),
  capture:  require('./assets/sounds/capture.wav'),
  check:    require('./assets/sounds/check.wav'),
  castle:   require('./assets/sounds/castle.wav'),
  gameover: require('./assets/sounds/gameover.wav'),
};
// Each sound gets a small pool of players that rotate, so a rapid second
// play never waits on the previous player's (async) seek to finish.
const POOL = 3;
let players = null, poolIdx = {};

function initAudio() {
  if (players) return;
  try { setAudioModeAsync({ playsInSilentMode: true, interruptionMode: 'mixWithOthers' }); } catch (e) {}
  try {
    const built = {};
    for (const k of Object.keys(SOUND_FILES)) {
      built[k] = Array.from({ length: POOL }, () => createAudioPlayer(SOUND_FILES[k]));
      poolIdx[k] = 0;
    }
    players = built;
  } catch (e) { players = null; }
}
function releaseAudio() {
  if (!players) return;
  try { Object.values(players).forEach(pool => pool.forEach(p => p.remove())); } catch (e) {}
  players = null; poolIdx = {};
}
function playSound(name) {
  if (!soundOn) return;
  try {
    if (!players) initAudio();
    const pool = players && players[name];
    if (!pool || !pool.length) return;
    const p = pool[poolIdx[name] % pool.length];
    poolIdx[name] = (poolIdx[name] + 1) % pool.length;
    try { p.seekTo(0); } catch (e) {}
    p.play();
  } catch (e) {}
}

// ══════════════════════════════════════════════
//  Move generation
// ══════════════════════════════════════════════
function getLegalMoves(row, col) {
  const p = gameBoard[row][col];
  let moves = getRaw(row, col);
  if (p === '♔' || p === '♚') moves = [...moves, ...getCastlingMoves()];
  if (p === '♙' || p === '♟') moves = [...moves, ...getEnPassantMoves(row, col)];
  return moves.filter(([r, c]) => !leavesInCheck(row, col, r, c));
}
// Pre-move targets: pseudo-legal, ignores whose turn it is
function premoveTargets(row, col) {
  const p = gameBoard[row][col];
  if (p === '♙' || p === '♟') {
    const dir = p === '♙' ? -1 : 1, start = p === '♙' ? 6 : 1, moves = [];
    if (inBounds(row+dir, col) && isEmpty(row+dir, col)) {
      moves.push([row+dir, col]);
      if (row === start && isEmpty(row+2*dir, col)) moves.push([row+2*dir, col]);
    }
    for (const dc of [-1,1]) if (inBounds(row+dir, col+dc)) moves.push([row+dir, col+dc]);
    return moves;
  }
  return getRaw(row, col);
}
function getRaw(row, col) {
  const p = gameBoard[row][col];
  if (p === '♙') return pawnMoves(row, col, 'white');
  if (p === '♟') return pawnMoves(row, col, 'black');
  if (p === '♖' || p === '♜') return slideMoves(row, col, [[-1,0],[1,0],[0,-1],[0,1]]);
  if (p === '♘' || p === '♞') return jumpMoves(row, col, [[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]]);
  if (p === '♗' || p === '♝') return slideMoves(row, col, [[-1,-1],[-1,1],[1,-1],[1,1]]);
  if (p === '♕' || p === '♛') return slideMoves(row, col, [[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[-1,1],[1,-1],[1,1]]);
  if (p === '♔' || p === '♚') return jumpMoves(row, col, [[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]]);
  return [];
}
function pawnMoves(row, col, color) {
  const moves = [], dir = color === 'white' ? -1 : 1, start = color === 'white' ? 6 : 1, p = gameBoard[row][col];
  if (inBounds(row+dir, col) && isEmpty(row+dir, col)) {
    moves.push([row+dir, col]);
    if (row === start && isEmpty(row+2*dir, col)) moves.push([row+2*dir, col]);
  }
  for (const dc of [-1,1]) if (inBounds(row+dir, col+dc) && isEnemy(p, gameBoard[row+dir][col+dc])) moves.push([row+dir, col+dc]);
  return moves;
}
function slideMoves(row, col, dirs) {
  const moves = [], p = gameBoard[row][col];
  for (const [dr, dc] of dirs) {
    let r = row+dr, c = col+dc;
    while (inBounds(r, c)) {
      if (isEmpty(r, c)) moves.push([r, c]);
      else { if (isEnemy(p, gameBoard[r][c])) moves.push([r, c]); break; }
      r += dr; c += dc;
    }
  }
  return moves;
}
function jumpMoves(row, col, jumps) {
  const p = gameBoard[row][col];
  return jumps.map(([dr,dc]) => [row+dr, col+dc]).filter(([r,c]) => inBounds(r,c) && (isEmpty(r,c) || isEnemy(p, gameBoard[r][c])));
}
function getEnPassantMoves(row, col) {
  if (!enPassantTarget) return [];
  const p = gameBoard[row][col], dir = isWhite(p) ? -1 : 1, [er, ec] = enPassantTarget;
  return (row+dir === er && Math.abs(col-ec) === 1) ? [[er, ec]] : [];
}
function getCastlingMoves() {
  const moves = [], color = currentTurn, row = color === 'white' ? 7 : 0;
  const king = color === 'white' ? '♔' : '♚', enemy = color === 'white' ? 'black' : 'white';
  if (gameBoard[row][4] !== king || isAttacked(row, 4, enemy)) return moves;
  if ((color === 'white' ? castlingRights.whiteKing : castlingRights.blackKing))
    if (isEmpty(row,5) && isEmpty(row,6) && !isAttacked(row,5,enemy) && !isAttacked(row,6,enemy)) moves.push([row,6]);
  if ((color === 'white' ? castlingRights.whiteQueen : castlingRights.blackQueen))
    if (isEmpty(row,3) && isEmpty(row,2) && isEmpty(row,1) && !isAttacked(row,3,enemy) && !isAttacked(row,2,enemy)) moves.push([row,2]);
  return moves;
}

// ══════════════════════════════════════════════
//  Check detection
// ══════════════════════════════════════════════
function findKing(color) {
  const k = color === 'white' ? '♔' : '♚';
  for (let r=0;r<8;r++) for (let c=0;c<8;c++) if (gameBoard[r][c] === k) return [r,c];
  return null;
}
function isAttacked(row, col, byColor) {
  for (let r=0;r<8;r++) for (let c=0;c<8;c++) {
    const p = gameBoard[r][c]; if (!p) continue;
    if (byColor === 'white' && !isWhite(p)) continue;
    if (byColor === 'black' && !isBlack(p)) continue;
    if (getRaw(r,c).some(([mr,mc]) => mr === row && mc === col)) return true;
  }
  return false;
}
function isInCheck(color) {
  const k = findKing(color);
  return k ? isAttacked(k[0], k[1], color === 'white' ? 'black' : 'white') : false;
}
function leavesInCheck(fr, fc, tr, tc) {
  const sf = gameBoard[fr][fc], st = gameBoard[tr][tc];
  gameBoard[tr][tc] = sf; gameBoard[fr][fc] = '';
  const r = isInCheck(currentTurn);
  gameBoard[fr][fc] = sf; gameBoard[tr][tc] = st;
  return r;
}
function noLegalMoves(color) {
  for (let r=0;r<8;r++) for (let c=0;c<8;c++) {
    const p = gameBoard[r][c]; if (!p) continue;
    if (color === 'white' && !isWhite(p)) continue;
    if (color === 'black' && !isBlack(p)) continue;
    if (getLegalMoves(r,c).length > 0) return false;
  }
  return true;
}
function insufficientMaterial() {
  const pieces = [];
  for (let r=0;r<8;r++) for (let c=0;c<8;c++) if (gameBoard[r][c]) pieces.push(gameBoard[r][c]);
  if (pieces.length === 2) return true;
  if (pieces.length === 3 && pieces.some(p => '♘♞♗♝'.includes(p))) return true;
  return false;
}

// ══════════════════════════════════════════════
//  Notation (SAN) + repetition
// ══════════════════════════════════════════════
function assembleSAN() {
  const p = pendingSAN; if (!p) return '?';
  if (p.castle) return p.tc === 6 ? 'O-O' : 'O-O-O';
  const cols = 'abcdefgh', dest = cols[p.tc] + (8 - p.tr);
  const isPawn = (p.piece === '♙' || p.piece === '♟');
  if (isPawn) {
    let s = (p.cap ? cols[p.fc] + 'x' : '') + dest;
    if (p.tr === 0 || p.tr === 7) s += '=' + SAN_LETTER[gameBoard[p.tr][p.tc]];
    return s;
  }
  return SAN_LETTER[p.piece] + p.disamb + (p.cap ? 'x' : '') + dest;
}
function disambiguation(fr, fc, tr, tc, piece) {
  const cols = 'abcdefgh', others = [];
  for (let r=0;r<8;r++) for (let c=0;c<8;c++) {
    if (r === fr && c === fc) continue;
    if (gameBoard[r][c] !== piece) continue;
    if (getLegalMoves(r,c).some(([mr,mc]) => mr === tr && mc === tc)) others.push([r,c]);
  }
  if (!others.length) return '';
  if (!others.some(([r,c]) => c === fc)) return cols[fc];
  if (!others.some(([r,c]) => r === fr)) return '' + (8 - fr);
  return cols[fc] + (8 - fr);
}
function positionKey() {
  let s = gameBoard.map(r => r.map(c => c || '.').join('')).join('/');
  s += ' ' + currentTurn[0];
  s += ' ' + (castlingRights.whiteKing?'K':'') + (castlingRights.whiteQueen?'Q':'') + (castlingRights.blackKing?'k':'') + (castlingRights.blackQueen?'q':'');
  s += ' ' + (enPassantTarget ? enPassantTarget.join(',') : '-');
  return s;
}

// ══════════════════════════════════════════════
//  Bot (Minimax + Alpha-Beta + piece-square tables)
// ══════════════════════════════════════════════
const PST = {
  '♙': [[0,0,0,0,0,0,0,0],[50,50,50,50,50,50,50,50],[10,10,20,30,30,20,10,10],[5,5,10,25,25,10,5,5],[0,0,0,20,20,0,0,0],[5,-5,-10,0,0,-10,-5,5],[5,10,10,-20,-20,10,10,5],[0,0,0,0,0,0,0,0]],
  '♘': [[-50,-40,-30,-30,-30,-30,-40,-50],[-40,-20,0,0,0,0,-20,-40],[-30,0,10,15,15,10,0,-30],[-30,5,15,20,20,15,5,-30],[-30,0,15,20,20,15,0,-30],[-30,5,10,15,15,10,5,-30],[-40,-20,0,5,5,0,-20,-40],[-50,-40,-30,-30,-30,-30,-40,-50]],
};
function evaluate() {
  let s = 0;
  for (let r=0;r<8;r++) for (let c=0;c<8;c++) {
    const p = gameBoard[r][c]; if (!p) continue;
    const val = (PIECE_VALUES[p] || 0) * 100;
    let b = 0;
    if (p === '♙') b = PST['♙'][r][c]; if (p === '♟') b = -PST['♙'][7-r][c];
    if (p === '♘') b = PST['♘'][r][c]; if (p === '♞') b = -PST['♘'][7-r][c];
    s += isWhite(p) ? val + b : -(val + b);
  }
  return s;
}
function allMoves(color) {
  const moves = [];
  for (let r=0;r<8;r++) for (let c=0;c<8;c++) {
    const p = gameBoard[r][c]; if (!p) continue;
    if (color === 'white' && !isWhite(p)) continue;
    if (color === 'black' && !isBlack(p)) continue;
    getLegalMoves(r,c).forEach(([tr,tc]) => moves.push([r,c,tr,tc]));
  }
  return moves;
}
function minimax(depth, alpha, beta, maximizing) {
  if (depth === 0) return evaluate();
  const color = maximizing ? 'white' : 'black', moves = allMoves(color);
  if (!moves.length) return isInCheck(color) ? (maximizing ? -99999 : 99999) : 0;
  if (maximizing) {
    let best = -Infinity;
    for (const [fr,fc,tr,tc] of moves) {
      const s = gameBoard[tr][tc]; gameBoard[tr][tc] = gameBoard[fr][fc]; gameBoard[fr][fc] = '';
      best = Math.max(best, minimax(depth-1, alpha, beta, false));
      gameBoard[fr][fc] = gameBoard[tr][tc]; gameBoard[tr][tc] = s;
      alpha = Math.max(alpha, best); if (beta <= alpha) break;
    }
    return best;
  }
  let best = Infinity;
  for (const [fr,fc,tr,tc] of moves) {
    const s = gameBoard[tr][tc]; gameBoard[tr][tc] = gameBoard[fr][fc]; gameBoard[fr][fc] = '';
    best = Math.min(best, minimax(depth-1, alpha, beta, true));
    gameBoard[fr][fc] = gameBoard[tr][tc]; gameBoard[tr][tc] = s;
    beta = Math.min(beta, best); if (beta <= alpha) break;
  }
  return best;
}
function findBestMove(color, depth) {
  const moves = allMoves(color); if (!moves.length) return null;
  const maxing = color === 'white';
  let best = null, bestScore = maxing ? -Infinity : Infinity;
  for (const [fr,fc,tr,tc] of moves) {
    const s = gameBoard[tr][tc]; gameBoard[tr][tc] = gameBoard[fr][fc]; gameBoard[fr][fc] = '';
    const sc = minimax(depth-1, -Infinity, Infinity, !maxing);
    gameBoard[fr][fc] = gameBoard[tr][tc]; gameBoard[tr][tc] = s;
    if (maxing ? sc > bestScore : sc < bestScore) { bestScore = sc; best = [fr,fc,tr,tc]; }
  }
  return best;
}

// ══════════════════════════════════════════════
//  Component
// ══════════════════════════════════════════════
export default function App() {
  const [, setTick] = useState(0);
  const [gameId, setGameId] = useState(0);
  const render = () => setTick(t => t + 1);
  const histRef = useRef(null);

  // Load the sound players up front so the first move isn't delayed
  useEffect(() => { initAudio(); return releaseAudio; }, []);

  // ── Clock ──
  useEffect(() => {
    if (screen !== 'game') return;
    const id = setInterval(() => {
      if (over || noTimer) return;
      if (currentTurn === 'white') { whiteTime--; if (whiteTime <= 0) { whiteTime = 0; endGame('Black wins on time!', 'black'); } }
      else { blackTime--; if (blackTime <= 0) { blackTime = 0; endGame('White wins on time!', 'white'); } }
      render();
    }, 1000);
    return () => clearInterval(id);
  }, [gameId, screen]);

  const go = (s) => { screen = s; render(); };

  function startWithTime(minutes, inc) {
    startMinutes = minutes; startIncrement = inc; noTimer = minutes === 0; increment = inc;
    whiteTime = blackTime = minutes * 60;
    startGame(pendingMode, pendingDifficulty);
  }
  function rematch() {
    noTimer = startMinutes === 0; increment = startIncrement;
    whiteTime = blackTime = startMinutes * 60;
    startGame(gameMode, botDifficulty);
  }
  function startGame(mode, diff) {
    gameBoard = initialBoard.map(r => [...r]);
    currentTurn = 'white'; enPassantTarget = null; halfMoveClock = 0;
    castlingRights = { whiteKing:true, whiteQueen:true, blackKing:true, blackQueen:true };
    capturedByWhite = []; capturedByBlack = []; boardHistory = []; moveHistory = [];
    positionCounts = {}; lastMove = null; over = false; pendingSAN = null;
    gameMode = mode; botDifficulty = diff;
    selected = null; targets = []; promo = null; result = null; thinking = false;
    flipped = false; hint = null; premove = null; dragging = null;
    positionCounts[positionKey()] = 1;
    status = "White's turn"; screen = 'game';
    setGameId(g => g + 1); render();
  }

  // ── Board coordinates (relative to the board view — no absolute measuring) ──
  function localFromEvent(e) {
    const n = e.nativeEvent;
    return { lx: (n.locationX || 0) - BORDER, ly: (n.locationY || 0) - BORDER };
  }
  function squareFromLocal(lx, ly) {
    if (lx < 0 || ly < 0 || lx >= PLAY || ly >= PLAY) return null;
    const dr = Math.min(7, Math.max(0, Math.floor(ly / SQ)));
    const dc = Math.min(7, Math.max(0, Math.floor(lx / SQ)));
    return [flipped ? 7 - dr : dr, flipped ? 7 - dc : dc];
  }
  // true when the human may move right now
  const myTurn = () => !(gameMode === 'bot' && currentTurn === 'black');
  // true when we're waiting on the bot → pre-move window
  const premoveWindow = () => gameMode === 'bot' && currentTurn === 'black' && !over;
  const humanPiece = (p) => gameMode === 'bot' ? isWhite(p) : isCurrentPlayer(p);

  // ── Gestures: tap + hold-to-drag (+ pre-move) ──
  const pan = useRef(PanResponder.create({
    onStartShouldSetPanResponder: () => true,
    onMoveShouldSetPanResponder: () => true,

    onPanResponderGrant: (e, g) => {
      if (over || promo) return;
      const { lx, ly } = localFromEvent(e);
      dragStart = { lx, ly };
      const sq = squareFromLocal(lx, ly);
      dragMoved = false; hint = null;
      if (!sq) return;
      const [r, c] = sq, piece = gameBoard[r][c];
      const pm = premoveWindow();
      if (!pm && !myTurn()) return;

      if (piece && humanPiece(piece)) {
        selected = [r, c];
        targets = pm ? premoveTargets(r, c) : getLegalMoves(r, c);
        dragPremove = pm;
        if (pm) premove = null;              // starting a fresh pre-move
        dragging = { r, c, piece, x: lx, y: ly };
        render();
      }
    },

    onPanResponderMove: (e, g) => {
      if (!dragging || !dragStart) return;
      if (Math.abs(g.dx) > 6 || Math.abs(g.dy) > 6) dragMoved = true;
      dragging.x = dragStart.lx + g.dx;
      dragging.y = dragStart.ly + g.dy;
      render();
    },

    onPanResponderRelease: (e, g) => {
      const from = dragging ? [dragging.r, dragging.c] : null;
      const wasDrag = !!dragging && dragMoved;
      const pm = dragPremove;
      dragging = null;
      if (over || promo) { render(); return; }
      const sq = dragStart ? squareFromLocal(dragStart.lx + g.dx, dragStart.ly + g.dy) : null;
      const src = from || selected;

      // Dropped (or tapped) onto a target square
      if (sq && src) {
        const list = pm ? premoveTargets(src[0], src[1]) : getLegalMoves(src[0], src[1]);
        const sameSq = src[0] === sq[0] && src[1] === sq[1];
        if (!sameSq && list.some(([mr,mc]) => mr === sq[0] && mc === sq[1])) {
          if (pm) { premove = { fr: src[0], fc: src[1], tr: sq[0], tc: sq[1] }; selected = null; targets = []; render(); }
          else doMove(src[0], src[1], sq[0], sq[1]);
          return;
        }
        if (wasDrag && !sameSq) { render(); return; }   // bad drop → keep selection
      }

      // Plain tap on empty / enemy square → clear
      if (!wasDrag && sq) {
        const p = gameBoard[sq[0]][sq[1]];
        if (!(p && humanPiece(p))) { selected = null; targets = []; if (premoveWindow()) premove = null; }
      }
      render();
    },

    onPanResponderTerminate: () => { dragging = null; render(); },
  })).current;

  // ── Move execution ──
  function pushHistory() {
    boardHistory.push({
      board: gameBoard.map(r => [...r]),
      capturedByWhite: [...capturedByWhite], capturedByBlack: [...capturedByBlack],
      enPassantTarget, castlingRights: { ...castlingRights }, currentTurn, lastMove,
      halfMoveClock, moveHistory: [...moveHistory], positionCounts: { ...positionCounts },
    });
  }

  function doMove(fr, fc, tr, tc) {
    const piece = gameBoard[fr][fc], captured = gameBoard[tr][tc];
    let epCapture = false, castle = false;
    pushHistory();

    if ((piece === '♙' || piece === '♟') && enPassantTarget && tr === enPassantTarget[0] && tc === enPassantTarget[1] && !captured) {
      const cap = gameBoard[fr][tc]; gameBoard[fr][tc] = '';
      if (currentTurn === 'white') capturedByWhite.push(cap); else capturedByBlack.push(cap);
      epCapture = true;
    }
    if (piece === '♙' && fr === 6 && tr === 4) enPassantTarget = [5, tc];
    else if (piece === '♟' && fr === 1 && tr === 3) enPassantTarget = [2, tc];
    else enPassantTarget = null;

    if (piece === '♔' && fc === 4) {
      if (tc === 6) { gameBoard[7][5] = '♖'; gameBoard[7][7] = ''; castle = true; }
      if (tc === 2) { gameBoard[7][3] = '♖'; gameBoard[7][0] = ''; castle = true; }
      castlingRights.whiteKing = castlingRights.whiteQueen = false;
    }
    if (piece === '♚' && fc === 4) {
      if (tc === 6) { gameBoard[0][5] = '♜'; gameBoard[0][7] = ''; castle = true; }
      if (tc === 2) { gameBoard[0][3] = '♜'; gameBoard[0][0] = ''; castle = true; }
      castlingRights.blackKing = castlingRights.blackQueen = false;
    }
    if (piece === '♖') { if (fr===7 && fc===0) castlingRights.whiteQueen = false; if (fr===7 && fc===7) castlingRights.whiteKing = false; }
    if (piece === '♜') { if (fr===0 && fc===0) castlingRights.blackQueen = false; if (fr===0 && fc===7) castlingRights.blackKing = false; }

    if (captured && !epCapture) { if (currentTurn === 'white') capturedByWhite.push(captured); else capturedByBlack.push(captured); }
    halfMoveClock = (captured || epCapture || piece === '♙' || piece === '♟') ? 0 : halfMoveClock + 1;

    pendingSAN = { fr, fc, tr, tc, piece, cap: !!(captured || epCapture), castle, disamb: '' };
    if (piece !== '♙' && piece !== '♟' && !castle) pendingSAN.disamb = disambiguation(fr, fc, tr, tc, piece);

    gameBoard[tr][tc] = piece; gameBoard[fr][fc] = '';
    lastMove = { fromRow: fr, fromCol: fc, toRow: tr, toCol: tc };
    playSound(captured || epCapture ? 'capture' : castle ? 'castle' : 'move');
    buzz(captured || epCapture ? 28 : 12);

    const promoting = (piece === '♙' && tr === 0) || (piece === '♟' && tr === 7);
    if (promoting) {
      const botMoving = gameMode === 'bot' && currentTurn === 'black';
      if (botMoving || autoQueen) gameBoard[tr][tc] = currentTurn === 'white' ? '♕' : '♛';
      else { selected = null; targets = []; promo = { r: tr, c: tc, color: currentTurn }; render(); return; }
    }
    finishTurn();
  }

  function onPromoPick(pieceChar) {
    gameBoard[promo.r][promo.c] = pieceChar;
    promo = null;
    finishTurn();
  }

  function finishTurn() {
    selected = null; targets = []; hint = null;
    if (!noTimer && increment > 0) { if (currentTurn === 'white') whiteTime += increment; else blackTime += increment; }
    currentTurn = currentTurn === 'white' ? 'black' : 'white';

    let san = assembleSAN();
    if (isInCheck(currentTurn)) san += noLegalMoves(currentTurn) ? '#' : '+';
    moveHistory.push(san);
    const key = positionKey(); positionCounts[key] = (positionCounts[key] || 0) + 1;

    const stuck = noLegalMoves(currentTurn);
    if (stuck && isInCheck(currentTurn)) return endGame(`${currentTurn === 'white' ? 'Black' : 'White'} wins by checkmate!`, currentTurn === 'white' ? 'black' : 'white');
    if (stuck) return endGame("Stalemate — it's a draw!", 'draw');
    if (halfMoveClock >= 100) return endGame('Draw — 50-move rule', 'draw');
    if (positionCounts[key] >= 3) return endGame('Draw — threefold repetition', 'draw');
    if (insufficientMaterial()) return endGame('Draw — insufficient material', 'draw');

    if (isInCheck(currentTurn)) {
      playSound('check');
      status = `${currentTurn === 'white' ? 'White' : 'Black'} is in check!`;
    } else {
      status = `${currentTurn === 'white' ? 'White' : 'Black'}'s turn`;
    }
    render();

    if (gameMode === 'bot' && currentTurn === 'black') {
      thinking = true; render();
      setTimeout(botMove, 250);
    } else if (gameMode === 'bot' && currentTurn === 'white' && premove) {
      // Play the queued pre-move if it's still legal
      const pm = premove; premove = null;
      setTimeout(() => {
        if (over) return;
        if (getLegalMoves(pm.fr, pm.fc).some(([r,c]) => r === pm.tr && c === pm.tc)) doMove(pm.fr, pm.fc, pm.tr, pm.tc);
        else render();
      }, 180);
    }
  }

  function botMove() {
    if (over) return;
    const depth = botDifficulty === 'easy' ? 1 : botDifficulty === 'medium' ? 2 : 3;
    const best = findBestMove('black', depth);
    thinking = false;
    if (best) doMove(best[0], best[1], best[2], best[3]); else render();
  }

  function endGame(msg, winner) {
    over = true; thinking = false; premove = null; status = msg; result = msg;
    if (winner === 'white') score.white++; else if (winner === 'black') score.black++; else score.draws++;
    playSound('gameover'); buzz(60); render();
  }

  function undo() {
    if (!boardHistory.length) return;
    const n = gameMode === 'bot' && boardHistory.length >= 2 ? 2 : 1;
    for (let i = 0; i < n; i++) {
      const prev = boardHistory.pop(); if (!prev) break;
      gameBoard = prev.board; capturedByWhite = prev.capturedByWhite; capturedByBlack = prev.capturedByBlack;
      enPassantTarget = prev.enPassantTarget; castlingRights = prev.castlingRights;
      currentTurn = prev.currentTurn; lastMove = prev.lastMove; halfMoveClock = prev.halfMoveClock;
      moveHistory = prev.moveHistory; positionCounts = prev.positionCounts;
    }
    over = false; result = null; selected = null; targets = []; thinking = false; hint = null; premove = null;
    status = `${currentTurn === 'white' ? 'White' : 'Black'}'s turn`; render();
  }

  function showHint() {
    if (over || promo || !myTurn()) return;
    const best = findBestMove(currentTurn, 2);
    if (best) { hint = { fr: best[0], fc: best[1], tr: best[2], tc: best[3] }; render(); }
  }

  function resign() {
    endGame(`${currentTurn === 'white' ? 'Black' : 'White'} wins — ${currentTurn} resigned`, currentTurn === 'white' ? 'black' : 'white');
  }

  // ══════════════════════════════════════════
  //  Screens
  // ══════════════════════════════════════════
  const t = TH();

  if (screen === 'home') {
    return (
      <SafeAreaView style={styles.center}>
        <Text style={[styles.title, { color: t.accent }]}>♟ Shatranj</Text>
        <View style={styles.scoreBar}>
          <Text style={styles.scoreTxt}>⬜ {score.white}</Text>
          <Text style={styles.scoreTxt}>Draws {score.draws}</Text>
          <Text style={styles.scoreTxt}>⬛ {score.black}</Text>
        </View>
        <Text style={styles.subtitle}>Choose a game mode</Text>
        <Btn label="🤖  vs Bot" accent={t.accent} onPress={() => { pendingMode = 'bot'; go('difficulty'); }} />
        <Btn label="👥  vs Friend" accent={t.accent} onPress={() => { pendingMode = 'friend'; pendingDifficulty = ''; go('time'); }} />
        <Text style={styles.small}>Board Theme</Text>
        <View style={styles.themeRow}>
          {Object.keys(THEMES).map(name => (
            <Pressable key={name} onPress={() => { theme = name; render(); }}
              style={[styles.themeBtn, { backgroundColor: THEMES[name].dark, borderColor: theme === name ? '#fff' : 'transparent' }]}>
              <View style={[styles.themeHalf, { backgroundColor: THEMES[name].light }]} />
            </Pressable>
          ))}
        </View>
        <StatusBar style="light" />
      </SafeAreaView>
    );
  }

  if (screen === 'difficulty') {
    return (
      <SafeAreaView style={styles.center}>
        <Text style={[styles.title, { color: t.accent }]}>Select Difficulty</Text>
        <Btn label="🟢  Easy" accent={t.accent} onPress={() => { pendingDifficulty = 'easy'; go('time'); }} />
        <Btn label="🟡  Medium" accent={t.accent} onPress={() => { pendingDifficulty = 'medium'; go('time'); }} />
        <Btn label="🔴  Hard" accent={t.accent} onPress={() => { pendingDifficulty = 'hard'; go('time'); }} />
        <Btn label="← Back" subtle onPress={() => go('home')} />
        <StatusBar style="light" />
      </SafeAreaView>
    );
  }

  if (screen === 'time') {
    return (
      <SafeAreaView style={styles.center}>
        <Text style={[styles.title, { color: t.accent }]}>Time Control</Text>
        <Btn label="⚡  Bullet — 1 min" accent={t.accent} onPress={() => startWithTime(1, 0)} />
        <Btn label="🔥  Blitz — 3 + 2" accent={t.accent} onPress={() => startWithTime(3, 2)} />
        <Btn label="⏱  Blitz — 5 + 3" accent={t.accent} onPress={() => startWithTime(5, 3)} />
        <Btn label="🕐  Rapid — 10 min" accent={t.accent} onPress={() => startWithTime(10, 0)} />
        <Btn label="♾  No Timer" accent={t.accent} onPress={() => startWithTime(0, 0)} />
        <Btn label="← Back" subtle onPress={() => go(pendingMode === 'bot' ? 'difficulty' : 'home')} />
        <StatusBar style="light" />
      </SafeAreaView>
    );
  }

  // ── Game screen ──
  const checkSq = !over && gameBoard.length && isInCheck(currentTurn) ? findKing(currentTurn) : null;
  let wMat = 0, bMat = 0;
  for (let r=0;r<8;r++) for (let c=0;c<8;c++) {
    const p = gameBoard[r][c];
    if (isWhite(p)) wMat += PIECE_VALUES[p] || 0; else if (isBlack(p)) bMat += PIECE_VALUES[p] || 0;
  }
  const diff = wMat - bMat;
  const evalPct = 50 + 50 * Math.tanh(evaluate() / 500);

  return (
    <SafeAreaView style={styles.game}>
      <View style={[styles.topBar, { width: PLAY }]}>
        <Pressable onPress={() => go('home')}><Text style={[styles.link, { color: t.accent }]}>← Menu</Text></Pressable>
        <View style={styles.iconRow}>
          <IconBtn label="💡" onPress={showHint} />
          <IconBtn label="↩" onPress={undo} />
          <IconBtn label="⇅" onPress={() => { flipped = !flipped; render(); }} />
          <IconBtn label={autoQueen ? '♕' : '♙'} onPress={() => { autoQueen = !autoQueen; render(); }} active={autoQueen} />
          <IconBtn label={soundOn ? '🔊' : '🔇'} onPress={() => { soundOn = !soundOn; render(); }} />
          <IconBtn label="🏳" onPress={resign} danger />
        </View>
      </View>

      <Text style={styles.status}>
        {thinking ? 'Bot is thinking…' : status}{premove ? '   • pre-move set' : ''}
      </Text>

      {/* Evaluation bar */}
      <View style={[styles.evalBar, { width: PLAY }]}>
        <View style={{ width: `${Math.max(3, Math.min(97, evalPct))}%`, height: '100%', backgroundColor: '#f0f0f0' }} />
      </View>

      <View style={[styles.playerRow, { width: PLAY }]}>
        <Text style={styles.captured} numberOfLines={1}>
          {capturedByBlack.join(' ')}{diff < 0 ? `  +${-diff}` : ''}
        </Text>
        <Text style={[styles.clock, currentTurn === 'black' && { color: t.accent, borderWidth: 2, borderColor: t.accent }, !noTimer && blackTime <= 20 && styles.clockLow]}>{fmt(blackTime)}</Text>
      </View>

      {/* Board */}
      <View collapsable={false}
        style={[styles.board, { borderColor: t.accent }]} {...pan.panHandlers}>
        {Array.from({ length: 8 }).map((_, dr) => (
          <View key={dr} style={styles.row} pointerEvents="none">
            {Array.from({ length: 8 }).map((_, dc) => {
              const r = flipped ? 7 - dr : dr, c = flipped ? 7 - dc : dc;
              const piece = gameBoard[r][c];
              const light = (r + c) % 2 === 0;
              const isSel = selected && selected[0] === r && selected[1] === c;
              const isTarget = targets.some(([mr,mc]) => mr === r && mc === c);
              const isLast = lastMove && ((lastMove.fromRow===r && lastMove.fromCol===c) || (lastMove.toRow===r && lastMove.toCol===c));
              const isHint = hint && ((hint.fr===r && hint.fc===c) || (hint.tr===r && hint.tc===c));
              const isPre = premove && ((premove.fr===r && premove.fc===c) || (premove.tr===r && premove.tc===c));
              const inCheck = checkSq && checkSq[0] === r && checkSq[1] === c;
              const held = dragging && dragging.r === r && dragging.c === c;
              let bg = light ? t.light : t.dark;
              if (isLast) bg = light ? '#f2ee9c' : '#d6cf65';
              if (isHint) bg = '#f6a600';
              if (isPre) bg = '#e8833a';
              if (isSel) bg = '#7fc97f';
              if (inCheck) bg = '#e2726e';
              return (
                <View key={dc} style={[styles.square, { backgroundColor: bg }]}>
                  {piece !== '' && !held && (
                    <Text style={[styles.piece, isWhite(piece) ? styles.whitePiece : styles.blackPiece]}>{piece}</Text>
                  )}
                  {isTarget && piece === '' && <View style={styles.dot} />}
                  {isTarget && piece !== '' && <View style={styles.ring} />}
                </View>
              );
            })}
          </View>
        ))}

        {/* Held piece follows your finger */}
        {dragging && (
          <Text pointerEvents="none" style={[
            styles.heldPiece,
            isWhite(dragging.piece) ? styles.whitePiece : styles.blackPiece,
            { left: dragging.x - SQ / 2, top: dragging.y - SQ / 2 },
          ]}>{dragging.piece}</Text>
        )}
      </View>

      <View style={[styles.playerRow, { width: PLAY }]}>
        <Text style={styles.captured} numberOfLines={1}>
          {capturedByWhite.join(' ')}{diff > 0 ? `  +${diff}` : ''}
        </Text>
        <Text style={[styles.clock, currentTurn === 'white' && { color: t.accent, borderWidth: 2, borderColor: t.accent }, !noTimer && whiteTime <= 20 && styles.clockLow]}>{fmt(whiteTime)}</Text>
      </View>

      {/* Move history */}
      <ScrollView ref={histRef} horizontal showsHorizontalScrollIndicator={false}
        onContentSizeChange={() => histRef.current && histRef.current.scrollToEnd({ animated: true })}
        style={[styles.histBar, { width: PLAY }]} contentContainerStyle={styles.histContent}>
        {moveHistory.length === 0
          ? <Text style={styles.histEmpty}>No moves yet</Text>
          : moveHistory.map((m, i) => (
              <Text key={i} style={styles.histMove}>{i % 2 === 0 ? `${i / 2 + 1}. ` : ''}{m}</Text>
            ))}
      </ScrollView>

      {/* Promotion picker */}
      {promo && (
        <View style={styles.overlay}>
          <View style={[styles.modal, { borderColor: t.accent }]}>
            <Text style={styles.modalTitle}>Promote to:</Text>
            <View style={styles.promoRow}>
              {(promo.color === 'white' ? ['♕','♖','♗','♘'] : ['♛','♜','♝','♞']).map(pc => (
                <Pressable key={pc} onPress={() => onPromoPick(pc)} style={styles.promoBtn}>
                  <Text style={[styles.promoPiece, promo.color === 'white' ? styles.whitePiece : styles.blackPiece]}>{pc}</Text>
                </Pressable>
              ))}
            </View>
          </View>
        </View>
      )}

      {/* Game over */}
      {result && (
        <View style={styles.overlay}>
          <View style={[styles.modal, { borderColor: t.accent }]}>
            <Text style={styles.modalIcon}>{/Draw|Stalemate/.test(result) ? '🤝' : '🏆'}</Text>
            <Text style={styles.modalTitle}>{result}</Text>
            <Text style={styles.scoreTxt}>⬜ {score.white}   Draws {score.draws}   ⬛ {score.black}</Text>
            <Btn label="▶  Play Again" accent={t.accent} onPress={rematch} />
            <Btn label="← Menu" subtle onPress={() => go('home')} />
          </View>
        </View>
      )}

      <StatusBar style="light" />
    </SafeAreaView>
  );
}

function Btn({ label, onPress, subtle, accent }) {
  return (
    <Pressable onPress={onPress} style={[styles.btn, subtle ? styles.btnSubtle : { backgroundColor: accent || '#e2b96f' }]}>
      <Text style={[styles.btnText, subtle && styles.btnTextSubtle]}>{label}</Text>
    </Pressable>
  );
}
function IconBtn({ label, onPress, danger, active }) {
  return (
    <Pressable onPress={onPress} style={[styles.iconBtn, danger && styles.danger, active && styles.iconActive]}>
      <Text style={styles.icon}>{label}</Text>
    </Pressable>
  );
}

// ══════════════════════════════════════════════
//  Styles
// ══════════════════════════════════════════════
const styles = StyleSheet.create({
  center: { flex: 1, backgroundColor: '#1a1a2e', alignItems: 'center', justifyContent: 'center', gap: 12, padding: 20 },
  game: { flex: 1, backgroundColor: '#1a1a2e', alignItems: 'center', paddingTop: 40, gap: 5 },
  title: { fontSize: 38, fontWeight: 'bold' },
  subtitle: { color: '#aaa', fontSize: 15 },
  small: { color: '#888', fontSize: 12, marginTop: 8 },
  scoreBar: { flexDirection: 'row', gap: 16, backgroundColor: '#16213e', paddingHorizontal: 16, paddingVertical: 6, borderRadius: 20 },
  scoreTxt: { color: '#ddd', fontSize: 13 },
  themeRow: { flexDirection: 'row', gap: 10 },
  themeBtn: { width: 40, height: 40, borderRadius: 8, borderWidth: 2, overflow: 'hidden' },
  themeHalf: { width: '100%', height: '50%' },
  btn: { paddingVertical: 12, paddingHorizontal: 26, borderRadius: 10, width: 230, alignItems: 'center' },
  btnText: { color: '#1a1a2e', fontSize: 16, fontWeight: 'bold' },
  btnSubtle: { backgroundColor: 'transparent' },
  btnTextSubtle: { color: '#aaa' },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  link: { fontSize: 15, fontWeight: 'bold' },
  iconRow: { flexDirection: 'row', gap: 4 },
  iconBtn: { backgroundColor: '#16213e', width: 32, height: 32, borderRadius: 7, alignItems: 'center', justifyContent: 'center' },
  iconActive: { backgroundColor: '#0f3460', borderWidth: 1, borderColor: '#e2b96f' },
  danger: { backgroundColor: '#c0392b' },
  icon: { color: '#fff', fontSize: 14 },
  status: { color: '#fff', fontSize: 15, fontWeight: 'bold', height: 20 },
  evalBar: { height: 7, backgroundColor: '#333', borderRadius: 4, overflow: 'hidden' },
  playerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  captured: { color: '#ddd', fontSize: 15, flex: 1 },
  clock: { color: '#aaa', fontSize: 17, fontWeight: 'bold', backgroundColor: '#16213e', paddingHorizontal: 9, paddingVertical: 2, borderRadius: 6, minWidth: 62, textAlign: 'center', overflow: 'hidden' },
  clockLow: { color: '#fff', backgroundColor: '#c0392b' },
  board: { width: PLAY + BORDER * 2, height: PLAY + BORDER * 2, borderWidth: BORDER },
  row: { flexDirection: 'row' },
  square: { width: SQ, height: SQ, alignItems: 'center', justifyContent: 'center' },
  piece: { fontSize: SQ * 0.66 },
  heldPiece: { position: 'absolute', width: SQ, height: SQ, fontSize: SQ * 0.8, textAlign: 'center', lineHeight: SQ },
  whitePiece: { color: '#ffffff', textShadowColor: '#000', textShadowRadius: 2, textShadowOffset: { width: 0, height: 0 } },
  blackPiece: { color: '#111111', textShadowColor: 'rgba(255,255,255,0.4)', textShadowRadius: 1, textShadowOffset: { width: 0, height: 0 } },
  dot: { position: 'absolute', width: SQ * 0.3, height: SQ * 0.3, borderRadius: SQ * 0.15, backgroundColor: 'rgba(0,0,0,0.25)' },
  ring: { position: 'absolute', top: SQ*0.05, left: SQ*0.05, width: SQ*0.9, height: SQ*0.9, borderRadius: SQ*0.45, borderWidth: 3, borderColor: 'rgba(0,0,0,0.25)' },
  histBar: { maxHeight: 34, backgroundColor: '#16213e', borderRadius: 7 },
  histContent: { alignItems: 'center', paddingHorizontal: 8, gap: 7 },
  histMove: { color: '#ddd', fontSize: 13 },
  histEmpty: { color: '#666', fontSize: 12 },
  overlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.78)', alignItems: 'center', justifyContent: 'center' },
  modal: { backgroundColor: '#16213e', borderWidth: 2, borderRadius: 14, padding: 22, alignItems: 'center', gap: 13 },
  modalIcon: { fontSize: 52 },
  modalTitle: { color: '#fff', fontSize: 17, fontWeight: 'bold', textAlign: 'center' },
  promoRow: { flexDirection: 'row', gap: 10 },
  promoBtn: { width: 56, height: 56, borderRadius: 8, backgroundColor: '#0f3460', alignItems: 'center', justifyContent: 'center' },
  promoPiece: { fontSize: 34 },
});
